### ISSUE TITLE
[MINT UI] Errors when selecting region in Use Models

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#237]
If I specify a region in the task for Agriculture, then the geospatial filtering does not work correctly. 
For example, in the following thread, I have specified Oromia as region:
https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/NeN3HjHHGDX6w5x3UKMA/G13wTLuuF1mDK8CZlNSA/datasets

However, the data catalog fails to provide resources with an error
![image](https://user-images.githubusercontent.com/1520666/73297242-0d3f4d00-41c0-11ea-8290-bf7db74c9f75.png)

If no region is specified, then the query works fine.

**Comment by dnfeldman** [comment]
I cannot reproduce this when invoking the API a single time with the payload that keeps failing in mint-ui. My only guess is that (if you look at network calls in chrome's development console), there are ~20-30 calls to `dataset_resources` happenings concurrently, resulting in AWS Gateway throttling requests and subsequently timing out. Unfortunately, I don't have control over this behavior. Instead, I would suggest @hvarg or @varunratnakar to:

1) stagger calls to `dataset_resources` (especially because it should be done for the selected dataset only) 
1.1) This will allow to populate results incrementally instead of "all or nothing" 

2) gracefully retry a few times on `504` response

3) gracefully handle situations when data catalog is still timing out (i.e., stop spinning and show some message so that the user isn't waiting forever

**Comment by hvarg** [comment]
I've changed the way the dataset resources are being loaded. 
Now, when you are editing, you will see 
"N total resources - Filter and Select"
N is the **total number of resources** in that dataset, not filtered by region.
When you click "Filter and select", it will load and filter the resources of that dataset and show you the select resources screen.

If you don't click these buttons, when you press "SELECT & CONTINUE" all resources for the selected datasets will be load so that can take a while...

Now we can have datasets that are returned for the first query but that actually has none of their resources in the selected region. 
@dgarijo Should we allow to save datasets with no resources?

**Comment by dgarijo** [comment]
Can datasets with no resources be executed? If they can't, then why show them?
Another story is that you can have datasets with 0 resources that are actually executable. See f14e9d03-2205-41e9-b685-0d9e6d064e6c

**Comment by hvarg** [comment]
How I can know if a dataset with 0 resources is executable?
I see one resource for https://dev.mint.isi.edu/ethiopia/datasets/browse/f14e9d03-2205-41e9-b685-0d9e6d064e6c

**Comment by dgarijo** [comment]
You can see one resource because Dan changed it so there would be one resource. You can have a dataset with 0 resources and pointing directly to the file (that is, in the dataset description itself). If we do not support datasets with zero resources, that's fine, but it needs to be documented. In any case, this is not directly related to the issue above.
