### ISSUE TITLE
Search model by region in UI

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mint-ui-lit#424]
Right now when you define a task, the region search just shows all models that are able to produce the variable, but it does not take into account the region in the filtering. It should

**Comment by varunratnakar** [comment]
Fixed with b22c24b
- Checks models for Task region first (example Oromia)
- Then checks models for the overall region (example Ethiopia)
- You can always view all models for the variable by clicking on "Show all models"

Caveat: The model_catalog_uri isn't present for many models in the graphql backend. If it is not present, we assume the url to be: https://w3id.org/okn/i/mint/<region_name_spaces_to_underscores>
